# Generated by Django 2.1.7 on 2019-05-11 21:03

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Charges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge', models.IntegerField()),
                ('paid', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
                ('phoneNumber', phone_field.models.PhoneField(help_text='Contact phone number', max_length=31, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='KeyMaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
                ('phoneNumber', phone_field.models.PhoneField(help_text='Contact phone number', max_length=31, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
                ('customerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CustomerRequests', to='webApp.Customer')),
                ('keymakerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='KeymakerRequests', to='webApp.KeyMaker')),
            ],
        ),
        migrations.AddField(
            model_name='charges',
            name='requestId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Charges', to='webApp.Request'),
        ),
    ]
